# Generated by Django 3.1 on 2020-09-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('heading0', models.CharField(max_length=500)),
                ('cheading0', models.CharField(max_length=50000)),
                ('image', models.ImageField(default='', upload_to='blog/images')),
                ('blog_pub_date', models.DateField()),
            ],
        ),
    ]
