# Generated by Django 3.1 on 2020-09-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cheading1',
            field=models.CharField(default='', max_length=50000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cheading2',
            field=models.CharField(default='', max_length=50000),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='cheading0',
            field=models.CharField(default='', max_length=50000),
        ),
    ]
