# Generated by Django 3.1 on 2020-09-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200908_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='heading1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='heading2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='heading0',
            field=models.CharField(default='', max_length=500),
        ),
    ]
