# Generated by Django 3.1 on 2020-09-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200908_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('Hello', 'hi'), ('bello', 'bye')], default='', max_length=50),
        ),
    ]
