# Generated by Django 3.1 on 2020-09-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('cat1', 'Design'), ('cat2', 'interface'), ('cat3', 'shop'), ('cat4', 'suggestion')], default='', max_length=50),
        ),
    ]
