# Generated by Django 3.1 on 2020-08-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_id', models.AutoField(primary_key=True, serialize=False)),
                ('Product_name', models.CharField(max_length=50)),
                ('Product_descr', models.CharField(max_length=300)),
                ('Poduct_Pub_date', models.DateField()),
            ],
        ),
    ]
