# Generated by Django 3.1 on 2020-08-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200822_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_descr',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_name',
            field=models.CharField(max_length=100),
        ),
    ]
