# Generated by Django 3.1 on 2020-09-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('itemJSon', models.CharField(max_length=50000)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
