# Generated by Django 3.1 on 2020-09-01 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200901_0652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='zip',
            new_name='zip_code',
        ),
    ]
