# Generated by Django 3.1 on 2020-09-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
    ]
