# Generated by Django 3.1 on 2020-09-04 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20200904_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderupdate',
            name='thank',
        ),
    ]
