# Generated by Django 3.1 on 2020-09-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_remove_orderupdate_thank'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='anount',
            field=models.IntegerField(default=0),
        ),
    ]
