# Generated by Django 3.1 on 2020-09-10 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_order_anount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='anount',
            new_name='amount',
        ),
    ]
