# Generated by Django 3.1 on 2020-09-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20200910_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='itemsName',
            field=models.CharField(default='', max_length=500000),
        ),
    ]
