# Generated by Django 3.1 on 2020-09-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_order_itemsname'),
    ]

    operations = [
        migrations.CreateModel(
            name='O_file',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(default='', upload_to='shop/other_files')),
            ],
        ),
    ]
