# Generated by Django 3.1 on 2020-09-14 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_o_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='O_file',
        ),
    ]
